import { type CalendarAssignment } from '@components/calendar';

interface PlanningAssignment extends CalendarAssignment {
  projectId: string | number;
  allocatedHours: number;
}

export const mockPlanningAssignments: PlanningAssignment[] = [
  {
    id: 1,
    userId: 1,
    startDate: '2025-06-02',
    endDate: '2025-06-06',
    title: 'Frontend Development',
    status: 'active',
    priority: 'high',
    notes: 'Working on user interface components and responsive design',
    projectId: 1,
    allocatedHours: 8,
  },
  {
    id: 2,
    userId: 3,
    startDate: '2025-06-03',
    endDate: '2025-06-04',
    title: 'API Development',
    status: 'active',
    priority: 'high',
    notes: 'Building REST endpoints for user management',
    projectId: 1,
    allocatedHours: 6,
  },
  {
    id: 3,
    userId: 3,
    startDate: '2025-06-05',
    title: 'Code Review',
    status: 'active',
    priority: 'medium',
    notes: 'Review pull requests for authentication module',
    projectId: 2,
    allocatedHours: 4,
  },
  {
    id: 4,
    userId: 5,
    startDate: '2025-06-09',
    endDate: '2025-06-11',
    title: 'UI Design',
    status: 'active',
    priority: 'medium',
    notes: 'Design dashboard components and user flows',
    projectId: 3,
    allocatedHours: 7,
  },
  {
    id: 5,
    userId: 3,
    startDate: '2025-06-10',
    endDate: '2025-06-14',
    title: 'React Components',
    status: 'planned',
    priority: 'high',
    notes: 'Build reusable component library',
    projectId: 3,
    allocatedHours: 8,
  },
  {
    id: 6,
    userId: 1,
    startDate: '2025-06-12',
    endDate: '2025-06-13',
    title: 'Database Design',
    status: 'planned',
    priority: 'medium',
    notes: 'Design schema for new features',
    projectId: 4,
    allocatedHours: 6,
  },
  {
    id: 7,
    userId: 5,
    startDate: '2025-06-16',
    title: 'Project Planning',
    status: 'planned',
    priority: 'high',
    notes: 'Sprint planning and requirement analysis',
    projectId: 2,
    allocatedHours: 3,
  },
  {
    id: 8,
    userId: 3,
    startDate: '2025-06-17',
    endDate: '2025-06-19',
    title: 'Quality Assurance',
    status: 'planned',
    priority: 'medium',
    notes: 'Testing user registration and login flows',
    projectId: 1,
    allocatedHours: 6,
  },
  {
    id: 9,
    userId: 3,
    startDate: '2025-06-18',
    endDate: '2025-06-20',
    title: 'Full Stack Development',
    status: 'planned',
    priority: 'high',
    notes: 'End-to-end feature implementation',
    projectId: 4,
    allocatedHours: 8,
  },
  {
    id: 10,
    userId: 5,
    startDate: '2025-06-23',
    endDate: '2025-06-25',
    title: 'UX Research',
    status: 'planned',
    priority: 'medium',
    notes: 'User testing and feedback collection',
    projectId: 2,
    allocatedHours: 5,
  },
  {
    id: 11,
    userId: 1,
    startDate: '2025-06-24',
    title: 'Bug Fixes',
    status: 'planned',
    priority: 'low',
    notes: 'Fix reported issues from testing phase',
    projectId: 3,
    allocatedHours: 4,
  },
  {
    id: 12,
    userId: 3,
    startDate: '2025-06-25',
    endDate: '2025-06-27',
    title: 'DevOps Setup',
    status: 'planned',
    priority: 'high',
    notes: 'Set up CI/CD pipeline and deployment',
    projectId: 2,
    allocatedHours: 7,
  },
  {
    id: 13,
    userId: 5,
    startDate: '2025-06-30',
    title: 'Client Meeting',
    status: 'planned',
    priority: 'high',
    notes: 'Present monthly progress to stakeholders',
    projectId: 3,
    allocatedHours: 2,
  },
  {
    id: 14,
    userId: 1,
    startDate: '2025-06-01',
    title: 'Design System',
    status: 'completed',
    priority: 'medium',
    notes: 'Completed design system documentation',
    projectId: 5,
    allocatedHours: 4,
  },
  {
    id: 15,
    userId: 5,
    startDate: '2025-06-06',
    title: 'Server Migration',
    status: 'cancelled',
    priority: 'medium',
    notes: 'Cancelled due to budget constraints',
    projectId: 3,
    allocatedHours: 5,
  },
  {
    id: 16,
    userId: 5,
    startDate: '2025-06-11',
    title: 'Documentation',
    status: 'active',
    priority: 'low',
    notes: 'Update technical documentation and API docs',
    projectId: 1,
    allocatedHours: 3,
  },
  {
    id: 17,
    userId: 3,
    startDate: '2025-06-26',
    endDate: '2025-06-27',
    title: 'Performance Optimization',
    status: 'planned',
    priority: 'medium',
    notes: 'Optimize application performance and loading times',
    projectId: 1,
    allocatedHours: 6,
  },
  {
    id: 18,
    userId: 5,
    startDate: '2025-06-22',
    endDate: '2025-06-25',
    title: 'Team Coordination',
    status: 'planned',
    priority: 'high',
    notes: 'Coordinate between development teams and stakeholders',
    projectId: 4,
    allocatedHours: 4,
  },
];
