import { Stage, FunctionalArea, IUser } from '../types/types';

const mockUser: IUser = { id: 1, name: 'John Doe' };

export const ProjectFormFields = [
  {
    name: 'name',
    label: 'Name',
    rules: [{ required: true, message: 'Please enter a name' }],
  },
];

export const mockProjects = [
  {
    id: 1,
    name: 'Project A',
    description: 'Client onboarding and CRM setup.',
    stage: Stage.LEAD,
    functionalArea: FunctionalArea.AREA1,
    toPlan: true,
    commercialRegion: 'EMEA',
    commercialCountry: 'Germany',
    customerType: 'USG',
    customerDetails: {
      address: '123 Main St',
      name: 'Acme Corp',
      contact: 'Jane Smith',
    },
    pWin: 75.5,
    pGo: 60.0,
    totalContractValue: 1000000.0,
    division: 'MSS',
    expectedRfpDate: new Date('2024-07-01'),
    expectedRfqDate: new Date('2024-07-10'),
    expectedSubmissionDate: new Date('2024-08-01'),
    expectedAwardDate: new Date('2024-09-01'),
    expectedContractStartDate: new Date('2024-10-01'),
    owner: mockUser,
    ownerId: 1,
    createdBy: mockUser,
    createdById: 1,
    tasks: [],
    documents: [],
    notes: [],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 2,
    name: 'Project B',
    description: 'E-commerce platform development.',
    stage: Stage.QUALIFIED,
    functionalArea: FunctionalArea.AREA2,
    toPlan: false,
    commercialRegion: 'APAC',
    commercialCountry: 'Japan',
    customerType: 'Commercial',
    customerDetails: {
      address: '456 Market St',
      name: 'Beta Inc',
      contact: 'John Smith',
    },
    pWin: 60.0,
    pGo: 50.0,
    totalContractValue: 500000.0,
    division: 'GSS',
    expectedRfpDate: new Date('2024-08-01'),
    expectedRfqDate: new Date('2024-08-10'),
    expectedSubmissionDate: new Date('2024-09-01'),
    expectedAwardDate: new Date('2024-10-01'),
    expectedContractStartDate: new Date('2024-11-01'),
    owner: mockUser,
    ownerId: 1,
    createdBy: mockUser,
    createdById: 1,
    tasks: [],
    documents: [],
    notes: [],
    createdAt: new Date('2024-06-02'),
    updatedAt: new Date('2024-06-11'),
  },
  {
    id: 3,
    name: 'Project C',
    description: 'Internal tool for analytics.',
    stage: Stage.CLOSED_WON,
    functionalArea: FunctionalArea.AREA1,
    toPlan: true,
    commercialRegion: 'AMER',
    commercialCountry: 'USA',
    customerType: 'None USG',
    customerDetails: {
      address: '789 Broadway',
      name: 'Gamma LLC',
      contact: 'Alice Brown',
    },
    pWin: 80.0,
    pGo: 70.0,
    totalContractValue: 200000.0,
    division: 'MSS',
    expectedRfpDate: new Date('2024-09-01'),
    expectedRfqDate: new Date('2024-09-10'),
    expectedSubmissionDate: new Date('2024-10-01'),
    expectedAwardDate: new Date('2024-11-01'),
    expectedContractStartDate: new Date('2024-12-01'),
    owner: mockUser,
    ownerId: 1,
    createdBy: mockUser,
    createdById: 1,
    tasks: [],
    documents: [],
    notes: [],
    createdAt: new Date('2024-06-03'),
    updatedAt: new Date('2024-06-12'),
  },
];

export const projectStages: { [key: string]: { id: string; title: string }[] } =
  {
    1: [
      { id: 'lead', title: 'Lead' },
      { id: 'qualified', title: 'Qualified' },
      { id: 'proposal', title: 'Proposal' },
      { id: 'negotiation', title: 'Negotiation' },
      { id: 'closed-won', title: 'Closed Won' },
      { id: 'closed-lost', title: 'Closed Lost' },
    ],
    2: [
      { id: 'lead', title: 'Lead' },
      { id: 'qualified', title: 'Qualified' },
      { id: 'proposal', title: 'Proposal' },
      { id: 'closed-won', title: 'Closed Won' },
    ],
    3: [
      { id: 'lead', title: 'Lead' },
      { id: 'closed-won', title: 'Closed Won' },
    ],
  };
