export enum TaskType {
    FEATURE = 'FEATURE',
    BUG = 'BUG',
    CODE_REVIEW = 'CODE_REVIEW',
    TESTING = 'TESTING',
    DOCUMENTATION = 'DOCUMENTATION',
    REFACTOR = 'REFACTOR',
    MEETING = 'MEETING',
    DEPLOYMENT = 'DEPLOYMENT',
    RESEARCH = 'RESEARCH',
    OTHER = 'OTHER',
  }
  